### ISSUE TITLE
More styling options - are you still there?

### ISSUE THREAD

**Issue by ibanner** [saleandro/songkick-wp-plugin#9]
Hi @saleandro - Are you still welcoming contributions for this plugin? I'd really like to be able to add an option to remove the default styles for the dates, or perhaps offer the user to add some custom CSS for displaying the event.

Itay B

**Comment by saleandro** [comment]
Hi Itay

I'm still here, but not actively updating the project. I'm happy to review a pull request if you have one.

thanks!

**Comment by saleandro** [comment]
I'll close this issue for now. Happy to review your submission.
